### ISSUE TITLE
is-callable dependency missing from package.json

### ISSUE THREAD

**Issue by davedoesdev** [mathiasbynens/Array.from#46]
Latest code (after `git clone` and `npm install` in the directory)

```
> require('array.from')
Error: Cannot find module 'is-callable'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/node_modules/array.from/implementation.js:7:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by ljharb** [comment]
Thanks - this is in unreleased code (added in #35). Will fix in master.

(In general, `master` is unstable, and code should only be consumed from npm, not from git)
